[tool.poetry]
name = "iamzero-boto3"
version = "0.1.7"
description = "The AWS SDK for Python, instrumented with iam-zero"
authors = ["Chris Norman <chris@exponentlabs.io>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.17.54"
iamzero-botocore = "^0.1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
