[tool.poetry]
name = "iamzero_botocore"
version = "0.1.8"
description = "iam-zero instrumentation for AWS botocore"
authors = ["Chris Norman <chris@exponentlabs.io>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
botocore = "^1.20.54"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
